### ISSUE TITLE
7d.json demand power inconsistencies 

### ISSUE THREAD

**Issue by chienleng** [opennem/opennem#141]
JSON: https://data.opennem.org.au/v3/stats/au/NEM/NSW1/power/7d.json

<img width="724" alt="Screen Shot 2022-09-25 at 4 58 31 pm" src="https://user-images.githubusercontent.com/349944/192132124-2ce2c26c-d296-4ff7-98c6-3c7d969f87b6.png">

* `data_type` should be `power`
* id should have `.power`

**Comment by aleith** [comment]
I've been thinking forward to when I (hopefully) find the resources to use a fork of the openNEM codebase to represent energy models of future high RE grids like 90% and you see a lot of curtailment there. Would be worth thinking about how we distinguish between generation, power and demand because the difference between generation and demand can only be curtailment — or unserved energy in extreme cases where demand > generation (for simplicity sake including exports and storage discharge as "generation" in this nomenclature).

I might log a feature request to incorporate the potential for curtailment, we will soon be seeing rooftopPV curtailment in WA and probably elsewhere for grid stability reasons. AEMO now has the legislated power in WA to remotely turn PV exports off if it is impinging on the grid having a safe level of thermal generation, what they call "operational demand".

Wind is being curtailed already foreign WA by 22-28% on the northern transmission lines for constraint reasons. 

I don't know how this information could be made available as live data, but it would be great to be able to show constraint on live generation for OpenNEM, and at least have capacity to represent it in the back-end and front end data structures.

**Comment by nc9** [comment]
@aleith can you file that as another issue? if you like I can move it over into one and we can start the conversation there
