### ISSUE TITLE
Not picking up distillate fuel type on SWIS

### ISSUE THREAD

**Issue by deathtrapz** [opennem/opennem#258]
See that distillate is not being picked up on the SWIS dashboard. Though usage shows on AEMO WEM Dashboard
 
![WEM](https://user-images.githubusercontent.com/94504151/231326888-3051f9ce-ad56-4f1e-9a01-862a257e023f.PNG)
![Open NEM](https://user-images.githubusercontent.com/94504151/231326894-b5cb543d-d918-4d28-ab64-94b8048d1ffc.PNG)

**Comment by nc9** [comment]
Thanks for the report - this is likely a care of an unmapped facility

**Comment by simonhac** [comment]
we _need_ a way to ensure there's a big error in flashing lights if a facility is unmapped. ie. it should be impossible for this kind of event to go unnoticed / unhandled.

**Comment by nc9** [comment]
we do - it pops up in the slack `facility_seen` messages each day

this was a case of `NAMKKN_MERR_SG1` being mapped as `gas_ocgt` rather than distillate, and I assume that is because of it's name:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/39009487/231667870-e3a23c59-2095-48ba-afc1-96915f56b6c3.png">

fix is already on dev/prod and commit in pipeline

**Comment by simonhac** [comment]
ah, thanks… if it's incorrectly mapped we won't get an error.

if there is an unmapped DUID, what would you see here?

<img width="367" alt="image" src="https://user-images.githubusercontent.com/20500649/231910920-6956edbc-953a-4f9a-b716-9ac26baab7c4.png">

**Comment by nc9** [comment]
we're mapping distillate now and it's showing up on WEM
