### ISSUE TITLE
Temp mismatches time

### ISSUE THREAD

**Issue by rob-ioenegy** [opennem/opennem#30]
Temp on 1 day SA view shows temp does not reflect correct temp. See photo
![E032360C-0AA3-4363-8D94-49E17E4D6574](https://user-images.githubusercontent.com/66508224/133268722-df32cb08-a56e-448d-a767-57b9ed8703c5.png)

**Comment by nc9** [comment]
<img width="1055" alt="Screen Shot 2021-09-24 at 9 13 07 am" src="https://user-images.githubusercontent.com/39009487/134595788-46f5c385-3f00-4403-9e0d-35289e8ebcd6.png">
)

Fixed in `v3.7.10` which is rolling out right now. I noticed the spiky values while working on this and I think we might smooth them out - i'll compare with the BoM actuals to see if they have the same prominent spikes.

**Comment by nc9** [comment]
Just found the issue at #37 and I believe this might be related.
