### ISSUE TITLE
Split Muja and Kwinana Stations on the SWIS network 

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#84]
We should have logic that stations into:

Muja:

* Muja AB: 4 x 60MW
* Muja CD: 2 x 200 MW & 2 x 227 MW

Kwinana
* Coal generators
* Gas generators

Double check REL/GI parsers are doing this each time they run

**Comment by nc9** [comment]
#79 is related

**Comment by nc9** [comment]
@simonhac can you just clarify these - as committed at the moment

MUJA AB - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L27979

MUJA CD - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28100

Kwinana Newgen - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28423

Kwinana Swift - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28579

Kwinana Cogen - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L29439

**Comment by nc9** [comment]
@aleith does this split of Kwinana and MUJA units look right?

**Comment by simonhac** [comment]
i don't know whether the long retired coal units at kwinana is at the same phyical facility as the newer OCGTs. perhaps @aleith knows?


![Image](https://user-images.githubusercontent.com/20500649/212642333-a2935539-1f71-4228-884e-0c7132da9173.png)

**Comment by nc9** [comment]
https://data.wa.aemo.com.au/public/public-data/datafiles/facilities/facilities.csv

**Comment by aleith** [comment]
> i don't know whether the long retired coal units at kwinana is at the same phyical facility as the newer OCGTs. perhaps @aleith knows?
> 
> 
> ![Image](https://user-images.githubusercontent.com/20500649/212642333-a2935539-1f71-4228-884e-0c7132da9173.png)
> 
> 
apologies. i only just saw this in my phone notifications. 

i need to look into it, probably have to call someone. don't recall off-hand because Kwinana has a lot of gas plus the old coalers that got retired (i think ages ago) that was behind the meter power for the Alcoa Aluminium refinery if memory serves me correctly. only occasionally ever dispatched to grid if at all. i'll ask someone who should know, Monday.

**Comment by aleith** [comment]
> > i don't know whether the long retired coal units at kwinana is at the same phyical facility as the newer OCGTs. perhaps @aleith knows?
> > 
> > 
> > ![Image](https://user-images.githubusercontent.com/20500649/212642333-a2935539-1f71-4228-884e-0c7132da9173.png)
> > 
> > 
> apologies, @simonhac & @nc9 I only just saw this in my phone notifications. 
> 

@nc9 i think i already linked to my spreadsheet combining multiple sources didnt i? that was as far as i got disambiguating. Kwinana was one of the main problem areas -- as was Kalgoorlie.

**Comment by nc9** [comment]
thanks @aleith i'll check the spreadsheet now - we just need a logical way of representing these stations

**Comment by aleith** [comment]
by representation you mean in terms of distinguishing between them being retired/mothballed/decommissioned/demolished and site remediated? or something else l?

**Comment by aleith** [comment]
> @simonhac can you just clarify these - as committed at the moment
> 
> MUJA AB - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L27979
> 
> MUJA CD - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28100
> 
> Kwinana Newgen - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28423
> 
> Kwinana Swift - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L28579
> 
> Kwinana Cogen - https://github.com/opennem/opennem/blob/master/opennem/data/stations.json#L29439

Muja AB and MUJA CD looks good to me. Though please not that retirements dates for individual units are different for all of these.

I'm still checking on the GTs as I don't want to guess.

**Comment by aleith** [comment]
### Media Release concerning closure of Muja C units 5 & 6.
>It is expected around 30 workers will be affected by the closure of the first Muja C Unit 5 on October 1, 2022. The closure of this unit is expected to have minimal impact on coal production.
>A further 40-50 workers will be potentially impacted by the Muja C Unit 6 closing on October 1, 2024. 
https://www.mediastatements.wa.gov.au/Pages/McGowan/2019/08/Muja-Power-Station-in-Collie-to-be-scaled-back-from-2022.aspx

### Media Release concerning Muja D

>Collie Power Station will close in late-2027 and Muja D in late-2029. As previously announced, Muja C's Unit 5 will close later this year and Unit 6 in 2024.
https://www.mediastatements.wa.gov.au/Pages/McGowan/2022/06/State-owned-coal-power-stations-to-be-retired-by-2030.aspx

**Comment by aleith** [comment]
for future reference:
http://data.wa.aemo.com.au/#facilities

**Comment by simonhac** [comment]
thanks @aleith. 

time to mark MUJA_G5 as retired @nc9.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/20500649/214503140-88da167c-b791-460a-bbca-8b7fe306d60d.png">

**Comment by aleith** [comment]
also worth noting that Muja is in the Collie location (collie/bunbury region) while Kwinana is halfway bw collie and perth and a seperate municipal region.

**Comment by aleith** [comment]
maybe it would be worth having a hash table of urls that are source links for info in the database. that way any info like retirement and commissioning dates or change of ownership could be automatically be footnoted in the front end simply using the lookup table. if index==0 then no footnote otherwise append a footnote and link it to the footnotes at bottom of page or directly to the url in the hash/lookup table. 

make sense?

**Comment by aleith** [comment]
* emissions rating is a bit complicated to determine because it depends on usage regime as much as CF and model of unit. a coal unit that has to ramp twice a day uses much more fuel for same energy dispatched in the year as a unit used just in winter but not ramped daily. the hey would appear to have the same CF but the ramp drives the emissions intensity up. openNEM conceivably could calculate it on historical ramping data if you had the emissions at various levels. GE provide that info for GTs. same applies to GTs. prob too much of a headache though unless someone has done prior work in this area and the methodology can be copied.

**Comment by simonhac** [comment]
larger generators are required to report their annual emissions to the CER. we're happy to use that value divided by generation as the emissions intensity. it'll even out to be accurate enough over the course of a year.

**Comment by nc9** [comment]
> maybe it would be worth having a hash table of urls that are source links for info in the database. that way any info like capacity, emissions rating*, retirement and commissioning dates or change of ownership could be automatically be footnoted in the front end simply using the lookup table.
> 
> if index==0 then no footnote. if index >0 then append a footnote (a front end object that looks like [2] or ² ) and link it to the footnotes at bottom of page or directly to the url in the hash/lookup table.
> 
> many of the sources would be from same AEMO or CER document so a lookup table might make it easier/faster to provide this info to users.
> 
> make sense?

I'm going to open this as a separate issue! want to track the Muja / Kwinana split here

**Comment by aleith** [comment]
Is this a new issue now?
